# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(973, 610)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, -30, 981, 661))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("color: rgb(0, 255, 0);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/Black_Template.jpg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 351, 61))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images/initial.gif"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(600, 90, 421, 441))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("images/Iron_Template_1.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(210, 110, 461, 311))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("images/1876553.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(350, 170, 171, 191))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("images/jarvis-1.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(20, 150, 151, 191))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("images/64ebb007104825948e077233babe3fcb.gif"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(100, 450, 871, 161))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("images/Black_Template.jpg"))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(0, 450, 391, 161))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("images/___3.gif"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")


        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(650, 510, 47, 13))
        self.label_5.setObjectName("label_5")
        self.pushButton_1 = QtWidgets.QPushButton(Dialog)
        self.pushButton_1.setGeometry(QtCore.QRect(700, 510, 111, 51))
        self.pushButton_1.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"font: 22pt \"MS Shell Dlg 2\";")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(810, 510, 111, 51))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"font: 22pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(480, 20, 241, 51))
        self.textBrowser.setStyleSheet("background-color: transparent;\n"
                                 "border: none;\n"
                                 "color: white;\n"
                                 "font-size: 20px;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(720, 20, 241, 51))
        self.textBrowser_2.setStyleSheet("background-color: transparent;\n"
                                 "border: none;\n"
                                 "color: white;\n"
                                 "font-size: 20px;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_8.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_9.raise_()
        self.label_5.raise_()
        self.pushButton_1.raise_()
        self.pushButton_2.raise_()
        self.textBrowser.raise_()
        self.textBrowser_2.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_5.setText(_translate("Dialog", "TextLabel"))
        self.pushButton_1.setText(_translate("Dialog", "Start"))
        self.pushButton_2.setText(_translate("Dialog", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    jarvisUi = QtWidgets.QMainWindow()
    ui = Ui_Dialog()
    ui.setupUi(jarvisUi)
    # Set the title of the dialog
    jarvisUi.setWindowTitle("Jarvis")
    # Set the icon for the dialog
    jarvisUi.setWindowIcon(QtGui.QIcon("images/Iron_Template_1.gif"))
    jarvisUi.show()
    sys.exit(app.exec_())
